[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cqterrain"
version = "0.0.2"
authors = [
  { name="James Adams", email="inklink28@gmail.com" },
]
description = "CADQuery helper library"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/medicationforall/cqhelper"
"Bug Tracker" = "https://github.com/medicationforall/cqhelper/issues"
