from .octagonWithDots import octagon_with_dots
from .octagonWithDots import octagon_with_dots_2
from .basketweave import basketweave
from .star import star
from .windmill import windmill
from .plain import plain
from .chamferFrame import chamfer_frame
from .rivet import rivet
from .slot import slot
