from .make_magnet_outline import make_magnet_outline
from .circle import circle
from .circle_uneven import circle_uneven
from .circle_wood import circle_wood
from .ellipse import ellipse
from .ellipse_uneven import ellipse_uneven
from .ellipse_wood import ellipse_wood
from .rectangle import rectangle
from .rectangle_uneven import rectangle_uneven
from .rectangle_wood import rectangle_wood
from .slot import slot
from .slot_uneven import slot_uneven
from .slot_wood import slot_wood
from .hexagon import hexagon
from .hexagon_uneven import hexagon_uneven
from .hexagon_wood import hexagon_wood

from .base_irregular import base_irregular 
from .circle_irregular import circle_irregular
from .ellipse_irregular import ellipse_irregular
from .hexagon_irregular import hexagon_irregular
from .rectangle_irregular import rectangle_irregular
from .slot_irregular import slot_irregular